import os

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3

ASTEROID_SPLIT_ANGLE_MIN = 20
ASTEROID_SPLIT_ANGLE_MAX = 50
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2

SCORE_SMALL = 30
SCORE_MEDIUM = 20
SCORE_LARGE = 10
HIGH_SCORE_PATH = os.path.expanduser("~/.asteroids/highscore.json")
